site_name: PangaShift Documentation
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
      - Getting Started: user-guide/getting-started.md
      - Account-settings: user-guide/account-settings.md
      - Employee-management: user-guide/employee-management.md
      - Faq: user-guide/faq.md
      - Entegrations: user-guide/integrations.md
      - Managing-shifts: user-guide/managing-shifts.md
      - Notifications: user-guide/notifications.md
  - API Reference: api.md
  - About: about.md
